# Generated by Django 3.1.2 on 2020-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='default/anony.jpg', null=True, upload_to='profile_pictures/')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
