# Generated by Django 3.1.2 on 2020-11-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
