# Generated by Django 3.1.2 on 2020-11-15 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumni', '0011_story_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='hearts',
            field=models.ManyToManyField(related_name='heart', to=settings.AUTH_USER_MODEL),
        ),
    ]
