# Generated by Django 3.1.2 on 2020-11-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0014_auto_20201115_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='story',
            name='updated_at',
        ),
    ]
