# Generated by Django 3.1.2 on 2020-11-15 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0015_auto_20201115_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
