# Generated by Django 3.1.2 on 2020-10-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20201008_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='alumnae_registration',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
