# Generated by Django 3.1.2 on 2020-10-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alumnae_registration_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnae_registration',
            name='field',
        ),
    ]
