# Generated by Django 3.1.2 on 2020-10-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_remove_alumnae_registration_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='course',
        ),
        migrations.DeleteModel(
            name='courses',
        ),
        migrations.DeleteModel(
            name='field',
        ),
    ]
