# Generated by Django 3.1.2 on 2020-10-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_auto_20201009_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnae_registration',
            name='about',
            field=models.TextField(blank=True, max_length=14, null=True),
        ),
    ]
